#!/usr/bin/env python3
"""
ensure_bcc32_classic_conf.py
Ensures that a "BC-32-classic" target exists in 50-cppbuilder.conf.

BC-32-classic is a BCC32 (classic Borland C89) variant of BC-32:
  - cc = bcc32 (not bcc32c)
  - C89-only flags: -pr -w-8012 -w-8065 -w-8057
  - -O1 instead of -O2 (safer for classic compiler)
  - Case-collision renames via -D defines (no -include support)
  - lib paths use win32/ (not win32c/)

Run: python helpers/ensure_bcc32_classic_conf.py [--collision-header PATH]
  --collision-header PATH  Read #define renames from header file
                           Default: helpers/openssl_fix_case_collisions.h

Idempotent: does nothing if BC-32-classic already exists.
"""

import os
import re
import sys
import argparse

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.join(SCRIPT_DIR, '..')
OPENSSL_BRANCH = os.environ.get('OPENSSL_BRANCH', '4')
_OPENSSL_SRC = os.environ.get('OPENSSL_SRC') or os.path.join(PROJECT_ROOT, 'c_src', 'openssl')
CONF_PATH = os.path.join(_OPENSSL_SRC, 'Configurations', '50-cppbuilder.conf')
DEFAULT_HEADER = os.path.join(SCRIPT_DIR, 'openssl_fix_case_collisions.h')

MARKER = '"BC-32-classic"'


def read_collision_defines(header_path):
    """Parse #define OLD NEW lines from the collision header, skip the include guard."""
    defines = []
    with open(header_path, 'r') as f:
        for line in f:
            m = re.match(r'^\s*#define\s+(\w+)\s+(\w+)\s*$', line)
            if m:
                old, new = m.group(1), m.group(2)
                if old.startswith('FIX_CASE_'):
                    continue  # skip include guard
                defines.append((old, new))
    return defines


def build_target_block(collision_defines):
    """Generate the Perl hash for BC-32-classic."""

    # Format collision defines as Perl strings for the defines => add(...) list
    coll_defs = []
    for old, new in collision_defines:
        coll_defs.append(f'                                "{old}={new}"')

    lines = []
    lines.append('    # ---- BCC32 Classic (Borland C89, OMF output) ----')
    lines.append('    # Auto-generated by helpers/ensure_bcc32_classic_conf.py')
    lines.append('    # Requires pre-patched sources via helpers/patch_c89.py --apply')
    lines.append('    "BC-32-classic" => {')
    lines.append('        inherit_from     => [ "BASE_Windows" ],')
    lines.append('        sys_id           => "WIN32",')
    lines.append('        bn_ops           => "BN_LLONG",')
    lines.append('        thread_scheme    => "winthreads",')
    lines.append('        cc               => "bcc32",')
    lines.append('        CPP              => "cpp32 -oCON -Sc -Sr",')
    lines.append('        defines          => add("WIN32_LEAN_AND_MEAN", "OPENSSL_SYS_WIN32",')
    lines.append('                                "L_ENDIAN", "DSO_WIN32", "_stricmp=stricmp",')
    lines.append('                                "_strnicmp=strnicmp", "_malloca=malloc",')
    lines.append('                                "_freea=free", "_setmode=setmode",')
    lines.append('                                "OPENSSL_NO_LOCALE", "_locale_t=void*",')
    lines.append('                                "_WIN32_WINNT=0x0601", "_WSPIAPI_H_",')
    lines.append('                                "_MSTCPIP_",')
    lines.append('                                # Case-collision renames (bcc32 has no -include)')
    for i, d in enumerate(coll_defs):
        if i < len(coll_defs) - 1:
            lines.append(d + ',')
        else:
            lines.append(d + '),')
    lines.append('        cflags           => picker(default => add("-q -c -pr -w-8012 -w-8065 -w-8057",')
    lines.append('                                                  threads("-tM"),')
    lines.append('                                                  shared("-tR")),')
    lines.append('                                   debug   => "-Od -v -vi- -D_DEBUG",')
    lines.append('                                   release => "-O1"),')
    lines.append('        bin_cflags       => "-tWC",')
    lines.append('        lib_cflags       => shared("-tWD -D_WINDLL -D_DLL"),')
    lines.append('        coutflag         => "-o",')
    lines.append('')
    lines.append('        makedepcmd       => "cpp32 -oCON -Sx -Hp",')
    lines.append('        makedep_scheme   => "embarcadero",')
    lines.append('')
    lines.append('        LD               => "ilink32",')
    lines.append('        LDFLAGS          => picker(default => "-x -Gn -q -w-dup",')
    lines.append('                                   debug   => \'-j"$(BDS)\\lib\\win32\\debug" \' .')
    lines.append('                                              \'-L"$(BDS)\\lib\\win32\\debug" -v\',')
    lines.append('                                   release => \'-j"$(BDS)\\lib\\win32\\release" \' .')
    lines.append('                                              \'-L"$(BDS)\\lib\\win32\\release"\'),')
    lines.append('        bin_lflags       => "-ap -Tpe c0x32.obj wildargs.obj",')
    lines.append('        ldoutflag        => ",",')
    lines.append('        ldpostoutflag    => ",,",')
    lines.append('        ld_resp_delim    => " +\\n",')
    lines.append('        ex_libs          => add(sub {')
    lines.append('            my @ex_libs = ("import32.lib",')
    lines.append('                           ($disabled{shared}')
    lines.append('                            ? ($disabled{threads} ? "cw32.lib" : "cw32mt.lib")')
    lines.append('                            : ($disabled{threads} ? "cw32i.lib" : "cw32mti.lib")));')
    lines.append('            push @ex_libs, "ws2_32.lib" unless $disabled{sock};')
    lines.append('            return join(" ", @ex_libs);')
    lines.append('        }),')
    lines.append('        AR               => "tlib",')
    lines.append('        ARFLAGS          => "/P256 /N /u",')
    lines.append('        ar_resp_delim    => " &\\n",')
    lines.append('        RC               => "brcc32",')
    lines.append('        RCFLAGS          => \'-i"$(BDS)\\include\\windows\\sdk"\',')
    lines.append('        rcoutflag        => "-fo",')
    lines.append('        shared_target    => "win-shared",')
    lines.append('        shared_ldflag    => "-aa -Tpd c0d32.obj",')
    lines.append('        lddefflag        => ",",')
    lines.append('        ldresflag        => ",",')
    lines.append('        ld_implib_rule   => \'implib -a $< $**\',')
    lines.append('        dso_scheme       => "win32",')
    lines.append('        shared_defflag   => \'\',')
    lines.append('        perl_platform    => \'Windows::cppbuilder\',')
    lines.append('        uplink_arch      => \'common\',')
    lines.append('    },')
    return '\n'.join(lines)


def main():
    parser = argparse.ArgumentParser(description='Ensure BC-32-classic target in 50-cppbuilder.conf')
    parser.add_argument('--collision-header', default=DEFAULT_HEADER,
                        help='Path to the case-collision header (default: helpers/openssl_fix_case_collisions.h)')
    args = parser.parse_args()

    if not os.path.isfile(CONF_PATH):
        print(f"ERROR: {CONF_PATH} not found")
        sys.exit(1)

    with open(CONF_PATH, 'r') as f:
        content = f.read()

    if MARKER in content:
        print(f"BC-32-classic already present in {os.path.basename(CONF_PATH)} — nothing to do.")
        print(f"  (OPENSSL_BRANCH={OPENSSL_BRANCH})")
        return

    # Read collision defines
    collision_defines = read_collision_defines(args.collision_header)
    if not collision_defines:
        print(f"WARNING: No collision defines found in {args.collision_header}")

    # Build the target block
    block = build_target_block(collision_defines)

    # Insert after the BC-32 closing "},\n" and before "BC-64"
    # Find the line '    "BC-64" =>' and insert before it
    anchor = '    "BC-64" => {'
    if anchor not in content:
        print(f"ERROR: Cannot find BC-64 anchor in {os.path.basename(CONF_PATH)}")
        sys.exit(1)

    content = content.replace(anchor, block + '\n' + anchor)

    with open(CONF_PATH, 'w') as f:
        f.write(content)

    print(f"Injected BC-32-classic ({len(collision_defines)} collision defines) "
          f"into {os.path.basename(CONF_PATH)} (OPENSSL_BRANCH={OPENSSL_BRANCH})")


if __name__ == '__main__':
    main()
