/*
 * openssl_fix_case_collisions.h - Resolve case-insensitive symbol collisions
 *
 * Delphi's linker resolves symbols case-insensitively. OpenSSL uses
 * case-sensitive naming where internal functions (lowercase foo_bar)
 * collide with public API wrappers (uppercase FOO_bar) when compared
 * case-insensitively. This causes the linker to merge them, routing
 * public API calls to internal stubs that crash with stack overflow / AV.
 *
 * This header renames the internal (lowercase) function in each
 * colliding pair by appending an underscore suffix. Force-include
 * via /FI ensures all translation units see the rename consistently.
 *
 * AUTO-GENERATED by helpers/gen_case_collision_fixes.py
 * Manual edits will be overwritten on next --update run.
 *
 * Used by: build_openssl3_msvc_win32.bat (/FI)
 *          build_openssl3_cbuilder_win32.bat (/FI)
 *          build_openssl3_cbuilder_classic_win32.bat (/FI)
 */

#ifndef FIX_CASE_COLLISIONS_H
#define FIX_CASE_COLLISIONS_H

/* Provider internals */
#define ossl_lib_ctx_get_data            ossl_lib_ctx_get_data_
#define ossl_provider_get0_dispatch      ossl_provider_get0_dispatch_
#define ossl_provider_get_capabilities   ossl_provider_get_capabilities_
#define ossl_provider_get_params         ossl_provider_get_params_
#define ossl_provider_gettable_params    ossl_provider_gettable_params_
#define ossl_provider_query_operation    ossl_provider_query_operation_
#define ossl_provider_self_test          ossl_provider_self_test_
#define ossl_provider_unquery_operation  ossl_provider_unquery_operation_

/* BIO internals */
#define bio_ctrl     bio_ctrl_
#define bio_free     bio_free_
#define bio_new      bio_new_
#define bio_nread    bio_nread_
#define bio_nread0   bio_nread0_
#define bio_nwrite   bio_nwrite_
#define bio_nwrite0  bio_nwrite0_
#define bio_puts     bio_puts_
#define bio_read     bio_read_
#define bio_wait     bio_wait_
#define bio_write    bio_write_

/* SSL internals */
#define ssl_callback_ctrl  ssl_callback_ctrl_
#define ssl_ctrl           ssl_ctrl_
#define ssl_free           ssl_free_
#define ssl_new            ssl_new_
#define ssl_read           ssl_read_
#define ssl_session_dup    ssl_session_dup_
#define ssl_write          ssl_write_

/* EVP internals */
#define EVP_Cipher              EVP_Cipher_
#define evp_asym_cipher_free    evp_asym_cipher_free_
#define evp_asym_cipher_up_ref  evp_asym_cipher_up_ref_
#define evp_cipher_free         evp_cipher_free_
#define evp_cipher_up_ref       evp_cipher_up_ref_
#define evp_kdf_free            evp_kdf_free_
#define evp_kdf_up_ref          evp_kdf_up_ref_
#define evp_kem_free            evp_kem_free_
#define evp_kem_up_ref          evp_kem_up_ref_
#define evp_keyexch_free        evp_keyexch_free_
#define evp_keyexch_up_ref      evp_keyexch_up_ref_
#define evp_keymgmt_free        evp_keymgmt_free_
#define evp_keymgmt_up_ref      evp_keymgmt_up_ref_
#define evp_mac_final           evp_mac_final_
#define evp_mac_free            evp_mac_free_
#define evp_mac_up_ref          evp_mac_up_ref_
#define evp_md_free             evp_md_free_
#define evp_md_up_ref           evp_md_up_ref_
#define evp_pkey_keygen         evp_pkey_keygen_
#define evp_rand_free           evp_rand_free_
#define evp_rand_up_ref         evp_rand_up_ref_
#define evp_signature_free      evp_signature_free_
#define evp_signature_up_ref    evp_signature_up_ref_

/* Encoder/Decoder internals */
#define ossl_decoder_free    ossl_decoder_free_
#define ossl_decoder_up_ref  ossl_decoder_up_ref_
#define ossl_encoder_free    ossl_encoder_free_
#define ossl_encoder_up_ref  ossl_encoder_up_ref_

/* Error subsystem */
#define err_load_strings              err_load_strings_
#define err_set_debug                 err_set_debug_
#define err_set_error                 err_set_error_
#define ossl_err_load_crypto_strings  ossl_err_load_crypto_strings_

/* DH/DSA/RSA/ECDSA internals */
#define dh_bits            dh_bits_
#define dh_security_bits   dh_security_bits_
#define dsa_bits           dsa_bits_
#define dsa_do_sign        dsa_do_sign_
#define dsa_do_verify      dsa_do_verify_
#define dsa_security_bits  dsa_security_bits_
#define dsa_sign           dsa_sign_
#define dsa_sign_setup     dsa_sign_setup_
#define dsa_verify         dsa_verify_
#define ecdsa_sign         ecdsa_sign_
#define ecdsa_sign_setup   ecdsa_sign_setup_
#define ecdsa_verify       ecdsa_verify_
#define rsa_bits           rsa_bits_
#define rsa_security_bits  rsa_security_bits_
#define rsa_sign           rsa_sign_
#define rsa_verify         rsa_verify_

/* MAC/Hash internals */
#define hmac_final       hmac_final_
#define hmac_init        hmac_init_
#define hmac_size        hmac_size_
#define hmac_update      hmac_update_
#define poly1305_final   poly1305_final_
#define poly1305_init    poly1305_init_
#define poly1305_update  poly1305_update_
#define siphash_final    siphash_final_
#define siphash_init     siphash_init_
#define siphash_update   siphash_update_

/* PKCS12/RAND internals */
#define pkcs12_gen_mac     pkcs12_gen_mac_
#define pkcs12_setup_mac   pkcs12_setup_mac_
#define rand_get0_primary  rand_get0_primary_
#define rand_get0_private  rand_get0_private_
#define rand_get0_public   rand_get0_public_

/* BN internals */
#define bn_free        bn_free_
#define bn_new         bn_new_
#define bn_print       bn_print_
#define bn_secure_new  bn_secure_new_

/* EC ASN.1 */
#define d2i_ECPKParameters  d2i_ECPKParameters_
#define i2d_ECPKParameters  i2d_ECPKParameters_

/* HPKE/CMP internals */
#define ossl_cmp_pollRep_new  ossl_cmp_pollRep_new_
#define ossl_cmp_pollReq_new  ossl_cmp_pollReq_new_
#define ossl_hpke_str2suite   ossl_hpke_str2suite_

/* OCSP */
#define OCSP_crlID_new  OCSP_crlID_new_

/* Other */
#define cmac_final             cmac_final_
#define cmac_init              cmac_init_
#define cmac_update            cmac_update_
#define dtlsv1_client_method   dtlsv1_client_method_
#define dtlsv1_method          dtlsv1_method_
#define dtlsv1_server_method   dtlsv1_server_method_
#define dtlsv1_2_client_method dtlsv1_2_client_method_
#define dtlsv1_2_method        dtlsv1_2_method_
#define dtlsv1_2_server_method dtlsv1_2_server_method_
#define md4_final              md4_final_
#define md4_init               md4_init_
#define md4_update             md4_update_
#define md5_final              md5_final_
#define md5_init               md5_init_
#define md5_update             md5_update_
#define mdc2_final             mdc2_final_
#define mdc2_init              mdc2_init_
#define mdc2_update            mdc2_update_
#define nconf_get_section      nconf_get_section_
#define nconf_get_string       nconf_get_string_
#define obj_cmp                obj_cmp_
#define ossl_param_dup         ossl_param_dup_
#define packet_forward         packet_forward_
#define sha1_final             sha1_final_
#define sha1_init              sha1_init_
#define sha1_update            sha1_update_
#define sha224_final           sha224_final_
#define sha224_init            sha224_init_
#define sha224_update          sha224_update_
#define sha256_final           sha256_final_
#define sha256_init            sha256_init_
#define sha256_update          sha256_update_
#define sha384_final           sha384_final_
#define sha384_init            sha384_init_
#define sha384_update          sha384_update_
#define sha512_final           sha512_final_
#define sha512_init            sha512_init_
#define sha512_update          sha512_update_
#define tlsv1_1_server_method  tlsv1_1_server_method_
#define tlsv1_1_client_method  tlsv1_1_client_method_
#define tlsv1_1_method         tlsv1_1_method_
#define tlsv1_2_client_method  tlsv1_2_client_method_
#define tlsv1_2_method         tlsv1_2_method_
#define tlsv1_2_server_method  tlsv1_2_server_method_
#define tlsv1_client_method    tlsv1_client_method_
#define tlsv1_method           tlsv1_method_
#define tlsv1_server_method    tlsv1_server_method_
#define ts_resp_set_tst_info   ts_resp_set_tst_info_
#define ui_null                ui_null_
#define ui_openssl             ui_openssl_
#define x509_store_add_crl     x509_store_add_crl_
#define zero                   zero_

#endif /* FIX_CASE_COLLISIONS_H */
