; msc32_coff_bridges.asm - JMP bridges from COFF decorated names to Delphi OMF names
; Auto-generated by gen_msc32_coff_bridges.py
.386
.model flat

EXTERN AcquireSRWLockExclusive:NEAR
EXTERN AcquireSRWLockShared:NEAR
EXTERN CMAC_CTX_copy:NEAR
EXTERN CMAC_CTX_free:NEAR
EXTERN CMAC_CTX_get0_cipher_ctx:NEAR
EXTERN CMAC_CTX_new:NEAR
EXTERN CMAC_Final:NEAR
EXTERN CMAC_Init:NEAR
EXTERN CMAC_Update:NEAR
EXTERN CertCloseStore:NEAR
EXTERN CertFindCertificateInStore:NEAR
EXTERN CertFreeCertificateContext:NEAR
EXTERN CertOpenSystemStoreW:NEAR
EXTERN CloseHandle:NEAR
EXTERN ConvertFiberToThread:NEAR
EXTERN ConvertThreadToFiberEx:NEAR
EXTERN CreateFiberEx:NEAR
EXTERN CreateSemaphoreA:NEAR
EXTERN CryptAcquireContextW:NEAR
EXTERN CryptGenRandom:NEAR
EXTERN CryptReleaseContext:NEAR
EXTERN DeleteCriticalSection:NEAR
EXTERN DeleteFiber:NEAR
EXTERN DeregisterEventSource:NEAR
EXTERN EnterCriticalSection:NEAR
EXTERN FindClose:NEAR
EXTERN FindFirstFileW:NEAR
EXTERN FindNextFileW:NEAR
EXTERN FormatMessageA:NEAR
EXTERN FreeLibrary:NEAR
EXTERN GetACP:NEAR
EXTERN GetConsoleMode:NEAR
EXTERN GetCurrentProcessId:NEAR
EXTERN GetCurrentThreadId:NEAR
EXTERN GetEnvironmentVariableW:NEAR
EXTERN GetExitCodeThread:NEAR
EXTERN GetFileType:NEAR
EXTERN GetLastError:NEAR
EXTERN GetModuleHandleW:NEAR
EXTERN GetProcAddress:NEAR
EXTERN GetProcessWindowStation:NEAR
EXTERN GetStdHandle:NEAR
EXTERN GetSystemDirectoryA:NEAR
EXTERN GetSystemInfo:NEAR
EXTERN GetSystemTime:NEAR
EXTERN GetSystemTimeAsFileTime:NEAR
EXTERN GetUserObjectInformationW:NEAR
EXTERN InitializeCriticalSection:NEAR
EXTERN InitializeSRWLock:NEAR
EXTERN LeaveCriticalSection:NEAR
EXTERN LoadLibraryA:NEAR
EXTERN LoadLibraryW:NEAR
EXTERN MessageBoxW:NEAR
EXTERN MultiByteToWideChar:NEAR
EXTERN ReadConsoleA:NEAR
EXTERN ReadConsoleW:NEAR
EXTERN RegisterEventSourceW:NEAR
EXTERN ReleaseSRWLockExclusive:NEAR
EXTERN ReleaseSRWLockShared:NEAR
EXTERN ReleaseSemaphore:NEAR
EXTERN ReportEventW:NEAR
EXTERN SetConsoleMode:NEAR
EXTERN SetLastError:NEAR
EXTERN Sleep:NEAR
EXTERN SwitchToFiber:NEAR
EXTERN SystemTimeToFileTime:NEAR
EXTERN TlsAlloc:NEAR
EXTERN TlsFree:NEAR
EXTERN TlsGetValue:NEAR
EXTERN TlsSetValue:NEAR
EXTERN TryEnterCriticalSection:NEAR
EXTERN VirtualAlloc:NEAR
EXTERN VirtualFree:NEAR
EXTERN VirtualLock:NEAR
EXTERN VirtualProtect:NEAR
EXTERN WSACleanup:NEAR
EXTERN WSAGetLastError:NEAR
EXTERN WSAIoctl:NEAR
EXTERN WSASetLastError:NEAR
EXTERN WSASocketA:NEAR
EXTERN WSAStartup:NEAR
EXTERN WaitForSingleObject:NEAR
EXTERN WideCharToMultiByte:NEAR
EXTERN WriteFile:NEAR
EXTERN _GetCurrentFiber_impl:NEAR
EXTERN __acrt_iob_func:NEAR
EXTERN _beginthreadex:NEAR
EXTERN _chmod:NEAR
EXTERN _close:NEAR
EXTERN _endthreadex:NEAR
EXTERN _errno:NEAR
EXTERN _exit:NEAR
EXTERN _fileno:NEAR
EXTERN _fstat:NEAR
EXTERN _fstat64i32:NEAR
EXTERN _get_osfhandle:NEAR
EXTERN _getch:NEAR
EXTERN _lrotl:NEAR
EXTERN _lrotr:NEAR
EXTERN _lseek:NEAR
EXTERN _msvcrt_fprintf:NEAR
EXTERN _msvcrt_sscanf:NEAR
EXTERN _msvcrt_vsnprintf:NEAR
EXTERN _read:NEAR
EXTERN _setmode:NEAR
EXTERN _stat:NEAR
EXTERN _stat64i32:NEAR
EXTERN _strdup:NEAR
EXTERN _time64:NEAR
EXTERN _vsnprintf_s:NEAR
EXTERN _vsnwprintf:NEAR
EXTERN _wfopen:NEAR
EXTERN _write:NEAR
EXTERN accept:NEAR
EXTERN atoi:NEAR
EXTERN atol:NEAR
EXTERN bind:NEAR
EXTERN calloc:NEAR
EXTERN clearerr:NEAR
EXTERN closesocket:NEAR
EXTERN connect:NEAR
EXTERN fclose:NEAR
EXTERN feof:NEAR
EXTERN ferror:NEAR
EXTERN fflush:NEAR
EXTERN fgetc:NEAR
EXTERN fgets:NEAR
EXTERN fopen:NEAR
EXTERN fputc:NEAR
EXTERN fputs:NEAR
EXTERN fread:NEAR
EXTERN free:NEAR
EXTERN fseek:NEAR
EXTERN ftell:NEAR
EXTERN ftoul:NEAR
EXTERN fwrite:NEAR
EXTERN getenv:NEAR
EXTERN gethostbyaddr:NEAR
EXTERN gethostbyname:NEAR
EXTERN getnameinfo:NEAR
EXTERN getpeername:NEAR
EXTERN getservbyname:NEAR
EXTERN getservbyport:NEAR
EXTERN getsockname:NEAR
EXTERN getsockopt:NEAR
EXTERN htonl:NEAR
EXTERN htons:NEAR
EXTERN inet_addr:NEAR
EXTERN inet_ntoa:NEAR
EXTERN ioctlsocket:NEAR
EXTERN isdigit:NEAR
EXTERN isspace:NEAR
EXTERN listen:NEAR
EXTERN llmul:NEAR
EXTERN lludiv:NEAR
EXTERN llumod:NEAR
EXTERN malloc:NEAR
EXTERN memchr:NEAR
EXTERN memcmp:NEAR
EXTERN memcpy:NEAR
EXTERN memmove:NEAR
EXTERN memset:NEAR
EXTERN ntohs:NEAR
EXTERN ossl_cmac_init:NEAR
EXTERN qsort:NEAR
EXTERN raise_impl:NEAR
EXTERN realloc:NEAR
EXTERN recv:NEAR
EXTERN recvfrom:NEAR
EXTERN select:NEAR
EXTERN send:NEAR
EXTERN sendto:NEAR
EXTERN setbuf:NEAR
EXTERN setsockopt:NEAR
EXTERN shutdown:NEAR
EXTERN signal:NEAR
EXTERN socket:NEAR
EXTERN sprintf_s:NEAR
EXTERN strcat:NEAR
EXTERN strcat_s:NEAR
EXTERN strchr:NEAR
EXTERN strcmp:NEAR
EXTERN strcpy:NEAR
EXTERN strcpy_s:NEAR
EXTERN strcspn:NEAR
EXTERN strerror:NEAR
EXTERN strerror_s:NEAR
EXTERN strlen:NEAR
EXTERN strncmp:NEAR
EXTERN strncpy:NEAR
EXTERN strncpy_s:NEAR
EXTERN strpbrk:NEAR
EXTERN strrchr:NEAR
EXTERN strspn:NEAR
EXTERN strstr:NEAR
EXTERN strtol:NEAR
EXTERN strtoul:NEAR
EXTERN time:NEAR
EXTERN tolower:NEAR
EXTERN wcscpy:NEAR
EXTERN wcsstr:NEAR

.code

PUBLIC _memcpy
_memcpy PROC
    jmp memcpy
_memcpy ENDP

PUBLIC _memset
_memset PROC
    jmp memset
_memset ENDP

PUBLIC _memmove
_memmove PROC
    jmp memmove
_memmove ENDP

PUBLIC _memcmp
_memcmp PROC
    jmp memcmp
_memcmp ENDP

PUBLIC _memchr
_memchr PROC
    jmp memchr
_memchr ENDP

PUBLIC _strlen
_strlen PROC
    jmp strlen
_strlen ENDP

PUBLIC _strcmp
_strcmp PROC
    jmp strcmp
_strcmp ENDP

PUBLIC _strncmp
_strncmp PROC
    jmp strncmp
_strncmp ENDP

PUBLIC _strncpy
_strncpy PROC
    jmp strncpy
_strncpy ENDP

PUBLIC _strcpy
_strcpy PROC
    jmp strcpy
_strcpy ENDP

PUBLIC _strcat
_strcat PROC
    jmp strcat
_strcat ENDP

PUBLIC _strchr
_strchr PROC
    jmp strchr
_strchr ENDP

PUBLIC _strrchr
_strrchr PROC
    jmp strrchr
_strrchr ENDP

PUBLIC _strstr
_strstr PROC
    jmp strstr
_strstr ENDP

PUBLIC _strpbrk
_strpbrk PROC
    jmp strpbrk
_strpbrk ENDP

PUBLIC _strspn
_strspn PROC
    jmp strspn
_strspn ENDP

PUBLIC _strcspn
_strcspn PROC
    jmp strcspn
_strcspn ENDP

PUBLIC _strtol
_strtol PROC
    jmp strtol
_strtol ENDP

PUBLIC _strtoul
_strtoul PROC
    jmp strtoul
_strtoul ENDP

PUBLIC _atoi
_atoi PROC
    jmp atoi
_atoi ENDP

PUBLIC _atol
_atol PROC
    jmp atol
_atol ENDP

PUBLIC _tolower
_tolower PROC
    jmp tolower
_tolower ENDP

PUBLIC _isdigit
_isdigit PROC
    jmp isdigit
_isdigit ENDP

PUBLIC _isspace
_isspace PROC
    jmp isspace
_isspace ENDP

PUBLIC _malloc
_malloc PROC
    jmp malloc
_malloc ENDP

PUBLIC _calloc
_calloc PROC
    jmp calloc
_calloc ENDP

PUBLIC _realloc
_realloc PROC
    jmp realloc
_realloc ENDP

PUBLIC _free
_free PROC
    jmp free
_free ENDP

PUBLIC _fopen
_fopen PROC
    jmp fopen
_fopen ENDP

PUBLIC _fclose
_fclose PROC
    jmp fclose
_fclose ENDP

PUBLIC _fread
_fread PROC
    jmp fread
_fread ENDP

PUBLIC _fwrite
_fwrite PROC
    jmp fwrite
_fwrite ENDP

PUBLIC _fseek
_fseek PROC
    jmp fseek
_fseek ENDP

PUBLIC _ftell
_ftell PROC
    jmp ftell
_ftell ENDP

PUBLIC _feof
_feof PROC
    jmp feof
_feof ENDP

PUBLIC _ferror
_ferror PROC
    jmp ferror
_ferror ENDP

PUBLIC _clearerr
_clearerr PROC
    jmp clearerr
_clearerr ENDP

PUBLIC _fflush
_fflush PROC
    jmp fflush
_fflush ENDP

PUBLIC _fputc
_fputc PROC
    jmp fputc
_fputc ENDP

PUBLIC _fgetc
_fgetc PROC
    jmp fgetc
_fgetc ENDP

PUBLIC _fputs
_fputs PROC
    jmp fputs
_fputs ENDP

PUBLIC _fgets
_fgets PROC
    jmp fgets
_fgets ENDP

PUBLIC _setbuf
_setbuf PROC
    jmp setbuf
_setbuf ENDP

PUBLIC _fprintf
_fprintf PROC
    jmp _msvcrt_fprintf
_fprintf ENDP

PUBLIC _sscanf
_sscanf PROC
    jmp _msvcrt_sscanf
_sscanf ENDP

PUBLIC _qsort
_qsort PROC
    jmp qsort
_qsort ENDP

PUBLIC _signal
_signal PROC
    jmp signal
_signal ENDP

PUBLIC _raise
_raise PROC
    jmp raise_impl
_raise ENDP

PUBLIC _getenv
_getenv PROC
    jmp getenv
_getenv ENDP

PUBLIC _time
_time PROC
    jmp time
_time ENDP

PUBLIC _strerror
_strerror PROC
    jmp strerror
_strerror ENDP

PUBLIC _wcscpy
_wcscpy PROC
    jmp wcscpy
_wcscpy ENDP

PUBLIC _wcsstr
_wcsstr PROC
    jmp wcsstr
_wcsstr ENDP

PUBLIC __time64
__time64 PROC
    jmp _time64
__time64 ENDP

PUBLIC __lrotl
__lrotl PROC
    jmp _lrotl
__lrotl ENDP

PUBLIC __lrotr
__lrotr PROC
    jmp _lrotr
__lrotr ENDP

PUBLIC __close
__close PROC
    jmp _close
__close ENDP

PUBLIC __read
__read PROC
    jmp _read
__read ENDP

PUBLIC __write
__write PROC
    jmp _write
__write ENDP

PUBLIC __lseek
__lseek PROC
    jmp _lseek
__lseek ENDP

PUBLIC __fileno
__fileno PROC
    jmp _fileno
__fileno ENDP

PUBLIC __get_osfhandle
__get_osfhandle PROC
    jmp _get_osfhandle
__get_osfhandle ENDP

PUBLIC __setmode
__setmode PROC
    jmp _setmode
__setmode ENDP

PUBLIC __stat64i32
__stat64i32 PROC
    jmp _stat64i32
__stat64i32 ENDP

PUBLIC __fstat64i32
__fstat64i32 PROC
    jmp _fstat64i32
__fstat64i32 ENDP

PUBLIC __strdup
__strdup PROC
    jmp _strdup
__strdup ENDP

PUBLIC __errno
__errno PROC
    jmp _errno
__errno ENDP

PUBLIC __exit
__exit PROC
    jmp _exit
__exit ENDP

PUBLIC __getch
__getch PROC
    jmp _getch
__getch ENDP

PUBLIC __chmod
__chmod PROC
    jmp _chmod
__chmod ENDP

PUBLIC __fstat
__fstat PROC
    jmp _fstat
__fstat ENDP

PUBLIC __stat
__stat PROC
    jmp _stat
__stat ENDP

PUBLIC __wfopen
__wfopen PROC
    jmp _wfopen
__wfopen ENDP

PUBLIC __beginthreadex
__beginthreadex PROC
    jmp _beginthreadex
__beginthreadex ENDP

PUBLIC __endthreadex
__endthreadex PROC
    jmp _endthreadex
__endthreadex ENDP

PUBLIC __vsnprintf
__vsnprintf PROC
    jmp _msvcrt_vsnprintf
__vsnprintf ENDP

PUBLIC __vsnprintf_s
__vsnprintf_s PROC
    jmp _vsnprintf_s
__vsnprintf_s ENDP

PUBLIC __vsnwprintf
__vsnwprintf PROC
    jmp _vsnwprintf
__vsnwprintf ENDP

PUBLIC ___acrt_iob_func
___acrt_iob_func PROC
    jmp __acrt_iob_func
___acrt_iob_func ENDP

PUBLIC _sprintf_s
_sprintf_s PROC
    jmp sprintf_s
_sprintf_s ENDP

PUBLIC _strcat_s
_strcat_s PROC
    jmp strcat_s
_strcat_s ENDP

PUBLIC _strcpy_s
_strcpy_s PROC
    jmp strcpy_s
_strcpy_s ENDP

PUBLIC _strncpy_s
_strncpy_s PROC
    jmp strncpy_s
_strncpy_s ENDP

PUBLIC _strerror_s
_strerror_s PROC
    jmp strerror_s
_strerror_s ENDP

PUBLIC _GetCurrentFiber
_GetCurrentFiber PROC
    jmp _GetCurrentFiber_impl
_GetCurrentFiber ENDP

PUBLIC _CMAC_CTX_new
_CMAC_CTX_new PROC
    jmp CMAC_CTX_new
_CMAC_CTX_new ENDP

PUBLIC _CMAC_CTX_free
_CMAC_CTX_free PROC
    jmp CMAC_CTX_free
_CMAC_CTX_free ENDP

PUBLIC _CMAC_CTX_get0_cipher_ctx
_CMAC_CTX_get0_cipher_ctx PROC
    jmp CMAC_CTX_get0_cipher_ctx
_CMAC_CTX_get0_cipher_ctx ENDP

PUBLIC _CMAC_CTX_copy
_CMAC_CTX_copy PROC
    jmp CMAC_CTX_copy
_CMAC_CTX_copy ENDP

PUBLIC _CMAC_Init
_CMAC_Init PROC
    jmp CMAC_Init
_CMAC_Init ENDP

PUBLIC _CMAC_Update
_CMAC_Update PROC
    jmp CMAC_Update
_CMAC_Update ENDP

PUBLIC _CMAC_Final
_CMAC_Final PROC
    jmp CMAC_Final
_CMAC_Final ENDP

PUBLIC _ossl_cmac_init
_ossl_cmac_init PROC
    jmp ossl_cmac_init
_ossl_cmac_init ENDP

PUBLIC _llumod
_llumod PROC
    jmp llumod
_llumod ENDP

PUBLIC _lludiv
_lludiv PROC
    jmp lludiv
_lludiv ENDP

PUBLIC _llmul
_llmul PROC
    jmp llmul
_llmul ENDP

PUBLIC _ftoul
_ftoul PROC
    jmp ftoul
_ftoul ENDP

PUBLIC _CloseHandle@4
_CloseHandle@4 PROC
    jmp CloseHandle
_CloseHandle@4 ENDP

PUBLIC _ConvertFiberToThread@0
_ConvertFiberToThread@0 PROC
    jmp ConvertFiberToThread
_ConvertFiberToThread@0 ENDP

PUBLIC _ConvertThreadToFiberEx@8
_ConvertThreadToFiberEx@8 PROC
    jmp ConvertThreadToFiberEx
_ConvertThreadToFiberEx@8 ENDP

PUBLIC _CreateFiberEx@20
_CreateFiberEx@20 PROC
    jmp CreateFiberEx
_CreateFiberEx@20 ENDP

PUBLIC _DeleteCriticalSection@4
_DeleteCriticalSection@4 PROC
    jmp DeleteCriticalSection
_DeleteCriticalSection@4 ENDP

PUBLIC _DeleteFiber@4
_DeleteFiber@4 PROC
    jmp DeleteFiber
_DeleteFiber@4 ENDP

PUBLIC _EnterCriticalSection@4
_EnterCriticalSection@4 PROC
    jmp EnterCriticalSection
_EnterCriticalSection@4 ENDP

PUBLIC _FindClose@4
_FindClose@4 PROC
    jmp FindClose
_FindClose@4 ENDP

PUBLIC _FindFirstFileW@8
_FindFirstFileW@8 PROC
    jmp FindFirstFileW
_FindFirstFileW@8 ENDP

PUBLIC _FindNextFileW@8
_FindNextFileW@8 PROC
    jmp FindNextFileW
_FindNextFileW@8 ENDP

PUBLIC _FormatMessageA@28
_FormatMessageA@28 PROC
    jmp FormatMessageA
_FormatMessageA@28 ENDP

PUBLIC _FreeLibrary@4
_FreeLibrary@4 PROC
    jmp FreeLibrary
_FreeLibrary@4 ENDP

PUBLIC _GetACP@0
_GetACP@0 PROC
    jmp GetACP
_GetACP@0 ENDP

PUBLIC _GetEnvironmentVariableW@12
_GetEnvironmentVariableW@12 PROC
    jmp GetEnvironmentVariableW
_GetEnvironmentVariableW@12 ENDP

PUBLIC _GetFileType@4
_GetFileType@4 PROC
    jmp GetFileType
_GetFileType@4 ENDP

PUBLIC _GetLastError@0
_GetLastError@0 PROC
    jmp GetLastError
_GetLastError@0 ENDP

PUBLIC _GetModuleHandleW@4
_GetModuleHandleW@4 PROC
    jmp GetModuleHandleW
_GetModuleHandleW@4 ENDP

PUBLIC _GetProcAddress@8
_GetProcAddress@8 PROC
    jmp GetProcAddress
_GetProcAddress@8 ENDP

PUBLIC _GetProcessWindowStation@0
_GetProcessWindowStation@0 PROC
    jmp GetProcessWindowStation
_GetProcessWindowStation@0 ENDP

PUBLIC _GetStdHandle@4
_GetStdHandle@4 PROC
    jmp GetStdHandle
_GetStdHandle@4 ENDP

PUBLIC _GetSystemDirectoryA@8
_GetSystemDirectoryA@8 PROC
    jmp GetSystemDirectoryA
_GetSystemDirectoryA@8 ENDP

PUBLIC _GetSystemInfo@4
_GetSystemInfo@4 PROC
    jmp GetSystemInfo
_GetSystemInfo@4 ENDP

PUBLIC _InitializeCriticalSection@4
_InitializeCriticalSection@4 PROC
    jmp InitializeCriticalSection
_InitializeCriticalSection@4 ENDP

PUBLIC _LeaveCriticalSection@4
_LeaveCriticalSection@4 PROC
    jmp LeaveCriticalSection
_LeaveCriticalSection@4 ENDP

PUBLIC _LoadLibraryA@4
_LoadLibraryA@4 PROC
    jmp LoadLibraryA
_LoadLibraryA@4 ENDP

PUBLIC _LoadLibraryW@4
_LoadLibraryW@4 PROC
    jmp LoadLibraryW
_LoadLibraryW@4 ENDP

PUBLIC _MultiByteToWideChar@24
_MultiByteToWideChar@24 PROC
    jmp MultiByteToWideChar
_MultiByteToWideChar@24 ENDP

PUBLIC _SetLastError@4
_SetLastError@4 PROC
    jmp SetLastError
_SetLastError@4 ENDP

PUBLIC _Sleep@4
_Sleep@4 PROC
    jmp Sleep
_Sleep@4 ENDP

PUBLIC _SwitchToFiber@4
_SwitchToFiber@4 PROC
    jmp SwitchToFiber
_SwitchToFiber@4 ENDP

PUBLIC _TryEnterCriticalSection@4
_TryEnterCriticalSection@4 PROC
    jmp TryEnterCriticalSection
_TryEnterCriticalSection@4 ENDP

PUBLIC _VirtualAlloc@16
_VirtualAlloc@16 PROC
    jmp VirtualAlloc
_VirtualAlloc@16 ENDP

PUBLIC _VirtualFree@12
_VirtualFree@12 PROC
    jmp VirtualFree
_VirtualFree@12 ENDP

PUBLIC _VirtualLock@8
_VirtualLock@8 PROC
    jmp VirtualLock
_VirtualLock@8 ENDP

PUBLIC _VirtualProtect@16
_VirtualProtect@16 PROC
    jmp VirtualProtect
_VirtualProtect@16 ENDP

PUBLIC _WideCharToMultiByte@32
_WideCharToMultiByte@32 PROC
    jmp WideCharToMultiByte
_WideCharToMultiByte@32 ENDP

PUBLIC _WriteFile@20
_WriteFile@20 PROC
    jmp WriteFile
_WriteFile@20 ENDP

PUBLIC _DeregisterEventSource@4
_DeregisterEventSource@4 PROC
    jmp DeregisterEventSource
_DeregisterEventSource@4 ENDP

PUBLIC _RegisterEventSourceW@8
_RegisterEventSourceW@8 PROC
    jmp RegisterEventSourceW
_RegisterEventSourceW@8 ENDP

PUBLIC _ReportEventW@36
_ReportEventW@36 PROC
    jmp ReportEventW
_ReportEventW@36 ENDP

PUBLIC _GetUserObjectInformationW@20
_GetUserObjectInformationW@20 PROC
    jmp GetUserObjectInformationW
_GetUserObjectInformationW@20 ENDP

PUBLIC _MessageBoxW@16
_MessageBoxW@16 PROC
    jmp MessageBoxW
_MessageBoxW@16 ENDP

PUBLIC _accept@12
_accept@12 PROC
    jmp accept
_accept@12 ENDP

PUBLIC _bind@12
_bind@12 PROC
    jmp bind
_bind@12 ENDP

PUBLIC _closesocket@4
_closesocket@4 PROC
    jmp closesocket
_closesocket@4 ENDP

PUBLIC _connect@12
_connect@12 PROC
    jmp connect
_connect@12 ENDP

PUBLIC _gethostbyaddr@12
_gethostbyaddr@12 PROC
    jmp gethostbyaddr
_gethostbyaddr@12 ENDP

PUBLIC _gethostbyname@4
_gethostbyname@4 PROC
    jmp gethostbyname
_gethostbyname@4 ENDP

PUBLIC _getnameinfo@28
_getnameinfo@28 PROC
    jmp getnameinfo
_getnameinfo@28 ENDP

PUBLIC _getpeername@12
_getpeername@12 PROC
    jmp getpeername
_getpeername@12 ENDP

PUBLIC _getservbyname@8
_getservbyname@8 PROC
    jmp getservbyname
_getservbyname@8 ENDP

PUBLIC _getservbyport@8
_getservbyport@8 PROC
    jmp getservbyport
_getservbyport@8 ENDP

PUBLIC _getsockname@12
_getsockname@12 PROC
    jmp getsockname
_getsockname@12 ENDP

PUBLIC _getsockopt@20
_getsockopt@20 PROC
    jmp getsockopt
_getsockopt@20 ENDP

PUBLIC _htonl@4
_htonl@4 PROC
    jmp htonl
_htonl@4 ENDP

PUBLIC _htons@4
_htons@4 PROC
    jmp htons
_htons@4 ENDP

PUBLIC _inet_addr@4
_inet_addr@4 PROC
    jmp inet_addr
_inet_addr@4 ENDP

PUBLIC _inet_ntoa@4
_inet_ntoa@4 PROC
    jmp inet_ntoa
_inet_ntoa@4 ENDP

PUBLIC _ioctlsocket@12
_ioctlsocket@12 PROC
    jmp ioctlsocket
_ioctlsocket@12 ENDP

PUBLIC _listen@8
_listen@8 PROC
    jmp listen
_listen@8 ENDP

PUBLIC _ntohs@4
_ntohs@4 PROC
    jmp ntohs
_ntohs@4 ENDP

PUBLIC _recv@16
_recv@16 PROC
    jmp recv
_recv@16 ENDP

PUBLIC _recvfrom@24
_recvfrom@24 PROC
    jmp recvfrom
_recvfrom@24 ENDP

PUBLIC _select@20
_select@20 PROC
    jmp select
_select@20 ENDP

PUBLIC _send@16
_send@16 PROC
    jmp send
_send@16 ENDP

PUBLIC _sendto@24
_sendto@24 PROC
    jmp sendto
_sendto@24 ENDP

PUBLIC _setsockopt@20
_setsockopt@20 PROC
    jmp setsockopt
_setsockopt@20 ENDP

PUBLIC _shutdown@8
_shutdown@8 PROC
    jmp shutdown
_shutdown@8 ENDP

PUBLIC _socket@12
_socket@12 PROC
    jmp socket
_socket@12 ENDP

PUBLIC _WSACleanup@0
_WSACleanup@0 PROC
    jmp WSACleanup
_WSACleanup@0 ENDP

PUBLIC _WSAGetLastError@0
_WSAGetLastError@0 PROC
    jmp WSAGetLastError
_WSAGetLastError@0 ENDP

PUBLIC _WSASetLastError@4
_WSASetLastError@4 PROC
    jmp WSASetLastError
_WSASetLastError@4 ENDP

PUBLIC _WSAStartup@8
_WSAStartup@8 PROC
    jmp WSAStartup
_WSAStartup@8 ENDP

PUBLIC _ReleaseSemaphore@12
_ReleaseSemaphore@12 PROC
    jmp ReleaseSemaphore
_ReleaseSemaphore@12 ENDP

PUBLIC _WaitForSingleObject@8
_WaitForSingleObject@8 PROC
    jmp WaitForSingleObject
_WaitForSingleObject@8 ENDP

PUBLIC _GetCurrentThreadId@0
_GetCurrentThreadId@0 PROC
    jmp GetCurrentThreadId
_GetCurrentThreadId@0 ENDP

PUBLIC _GetExitCodeThread@8
_GetExitCodeThread@8 PROC
    jmp GetExitCodeThread
_GetExitCodeThread@8 ENDP

PUBLIC _CreateSemaphoreA@16
_CreateSemaphoreA@16 PROC
    jmp CreateSemaphoreA
_CreateSemaphoreA@16 ENDP

PUBLIC _InitializeSRWLock@4
_InitializeSRWLock@4 PROC
    jmp InitializeSRWLock
_InitializeSRWLock@4 ENDP

PUBLIC _ReleaseSRWLockExclusive@4
_ReleaseSRWLockExclusive@4 PROC
    jmp ReleaseSRWLockExclusive
_ReleaseSRWLockExclusive@4 ENDP

PUBLIC _ReleaseSRWLockShared@4
_ReleaseSRWLockShared@4 PROC
    jmp ReleaseSRWLockShared
_ReleaseSRWLockShared@4 ENDP

PUBLIC _AcquireSRWLockExclusive@4
_AcquireSRWLockExclusive@4 PROC
    jmp AcquireSRWLockExclusive
_AcquireSRWLockExclusive@4 ENDP

PUBLIC _AcquireSRWLockShared@4
_AcquireSRWLockShared@4 PROC
    jmp AcquireSRWLockShared
_AcquireSRWLockShared@4 ENDP

PUBLIC _TlsAlloc@0
_TlsAlloc@0 PROC
    jmp TlsAlloc
_TlsAlloc@0 ENDP

PUBLIC _TlsGetValue@4
_TlsGetValue@4 PROC
    jmp TlsGetValue
_TlsGetValue@4 ENDP

PUBLIC _TlsSetValue@8
_TlsSetValue@8 PROC
    jmp TlsSetValue
_TlsSetValue@8 ENDP

PUBLIC _TlsFree@4
_TlsFree@4 PROC
    jmp TlsFree
_TlsFree@4 ENDP

PUBLIC _GetSystemTime@4
_GetSystemTime@4 PROC
    jmp GetSystemTime
_GetSystemTime@4 ENDP

PUBLIC _SystemTimeToFileTime@8
_SystemTimeToFileTime@8 PROC
    jmp SystemTimeToFileTime
_SystemTimeToFileTime@8 ENDP

PUBLIC _GetCurrentProcessId@0
_GetCurrentProcessId@0 PROC
    jmp GetCurrentProcessId
_GetCurrentProcessId@0 ENDP

PUBLIC _GetSystemTimeAsFileTime@4
_GetSystemTimeAsFileTime@4 PROC
    jmp GetSystemTimeAsFileTime
_GetSystemTimeAsFileTime@4 ENDP

PUBLIC _GetConsoleMode@8
_GetConsoleMode@8 PROC
    jmp GetConsoleMode
_GetConsoleMode@8 ENDP

PUBLIC _SetConsoleMode@8
_SetConsoleMode@8 PROC
    jmp SetConsoleMode
_SetConsoleMode@8 ENDP

PUBLIC _ReadConsoleA@20
_ReadConsoleA@20 PROC
    jmp ReadConsoleA
_ReadConsoleA@20 ENDP

PUBLIC _ReadConsoleW@20
_ReadConsoleW@20 PROC
    jmp ReadConsoleW
_ReadConsoleW@20 ENDP

PUBLIC _CryptAcquireContextW@20
_CryptAcquireContextW@20 PROC
    jmp CryptAcquireContextW
_CryptAcquireContextW@20 ENDP

PUBLIC _CryptReleaseContext@8
_CryptReleaseContext@8 PROC
    jmp CryptReleaseContext
_CryptReleaseContext@8 ENDP

PUBLIC _CryptGenRandom@12
_CryptGenRandom@12 PROC
    jmp CryptGenRandom
_CryptGenRandom@12 ENDP

PUBLIC _CertCloseStore@8
_CertCloseStore@8 PROC
    jmp CertCloseStore
_CertCloseStore@8 ENDP

PUBLIC _CertFindCertificateInStore@24
_CertFindCertificateInStore@24 PROC
    jmp CertFindCertificateInStore
_CertFindCertificateInStore@24 ENDP

PUBLIC _CertFreeCertificateContext@4
_CertFreeCertificateContext@4 PROC
    jmp CertFreeCertificateContext
_CertFreeCertificateContext@4 ENDP

PUBLIC _CertOpenSystemStoreW@8
_CertOpenSystemStoreW@8 PROC
    jmp CertOpenSystemStoreW
_CertOpenSystemStoreW@8 ENDP

PUBLIC _WSAIoctl@36
_WSAIoctl@36 PROC
    jmp WSAIoctl
_WSAIoctl@36 ENDP

PUBLIC _WSASocketA@24
_WSASocketA@24 PROC
    jmp WSASocketA
_WSASocketA@24 ENDP

END